name: ee_py3
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - astroid=2.3.3=py37_0
  - attrs=19.3.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.7.22=0
  - cachetools=3.1.1=py_0
  - certifi=2020.6.20=py37_0
  - cffi=1.13.2=py37hb32ad35_0
  - cfitsio=3.470=he774522_5
  - chardet=3.0.4=py37_1003
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.2.2=py_1
  - colorama=0.4.1=py_0
  - cryptography=2.8=py37hb32ad35_0
  - curl=7.67.0=h2a8f88b_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.9=h33f27b4_2
  - fiona=1.8.13=py37hb7fdc2d_0
  - freexl=1.0.5=hfa6e2cd_0
  - gdal=3.0.2=py37hdf43c64_0
  - geopandas=0.8.1=py_0
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.5.1=h5770a2b_1
  - google-api-python-client=1.7.11=py_0
  - google-auth=1.7.0=py_0
  - google-auth-httplib2=0.0.3=py_2
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - httplib2=0.14.0=py37_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.8=py37_1000
  - imagesize=1.1.0=py_0
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2020.1=216
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.9.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - jpeg=9c=hfa6e2cd_1001
  - jsonschema=3.1.1=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py37_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.6.1=py37_0
  - kealib=1.4.7=h07cbb95_6
  - keyring=19.2.0=py37_0
  - krb5=1.16.4=hc04afaa_0
  - lazy-object-proxy=1.4.3=py37hfa6e2cd_0
  - libboost=1.67.0=hd9e427e_4
  - libclang=9.0.0=default_hf44288c_4
  - libcurl=7.67.0=h2a8f88b_0
  - libgdal=3.0.2=h1155b67_0
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=he5f2a48_4
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h7602738_0
  - libpq=11.2=h3235a2c_0
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialindex=1.9.3=he025d50_3
  - libspatialite=4.3.0a=h7ffb84d_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.10=h464c3ec_1
  - lz4-c=1.8.1.2=h2fa13f4_0
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - markupsafe=1.1.1=py37hfa6e2cd_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37hfa6e2cd_1000
  - mkl=2020.1=216
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.1.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - more-itertools=7.2.0=py_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py_1
  - notebook=6.0.1=py37_0
  - numpy-base=1.19.1=py37ha3acd2a_0
  - numpydoc=0.9.1=py_0
  - openjpeg=2.3.0=h5ec785f_1
  - openssl=1.1.1g=he774522_1
  - packaging=19.2=py_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - pcre=8.44=ha925a31_0
  - pickleshare=0.7.5=py37_1000
  - pip=20.2.2=py37_0
  - postgresql=11.2=h3235a2c_0
  - proj=6.2.1=h9f7ef89_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - psutil=5.6.5=py37hfa6e2cd_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.5.0=py_0
  - pycparser=2.19=py37_1
  - pycrypto=2.6.1=py37hfa6e2cd_1003
  - pyflakes=2.1.1=py_0
  - pygments=2.4.2=py_0
  - pylint=2.4.4=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.5=py_0
  - pyproj=2.4.2.post1=py37h9716dcf_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.15.5=py37hfa6e2cd_0
  - pysocks=1.7.1=py37_0
  - python=3.7.3=h510b542_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pywin32=225=py37hfa6e2cd_0
  - pywin32-ctypes=0.2.0=py37_1000
  - pywinpty=0.5.5=py37_1000
  - pyzmq=18.1.1=py37h16f9016_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=0.6.0=py_0
  - qtconsole=4.6.0=py_0
  - qtpy=1.9.0=py_0
  - requests=2.22.0=py37_1
  - rope=0.14.0=py_0
  - rsa=4.0=py_0
  - rtree=0.9.4=py37h804a536_1
  - send2trash=1.5.0=py_0
  - setuptools=41.6.0=py37_1
  - shapely=1.7.0=py37h13a63d7_1
  - simplejson=3.16.0=py37hfa6e2cd_1002
  - sip=4.19.8=py37h6538335_0
  - six=1.13.0=py37_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=2.2.1=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - spyder=3.3.6=py37_1
  - spyder-kernels=0.5.2=py37_0
  - sqlite=3.30.1=hfa6e2cd_0
  - tbb=2018.0.5=he980bc4_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tiledb=1.6.3=h7b000aa_0
  - tk=8.6.10=he774522_0
  - tornado=6.0.3=py37hfa6e2cd_0
  - traitlets=4.3.3=py37_0
  - uritemplate=3.0.0=py_1
  - urllib3=1.25.7=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_1003
  - winpty=0.4.3=4
  - wrapt=1.11.2=py37hfa6e2cd_0
  - xerces-c=3.2.2=ha925a31_0
  - xz=5.2.5=h62dcd97_0
  - zeromq=4.3.2=h6538335_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.3.7=h508b16e_0
  - pip:
    - absl-py==0.10.0
    - arcgis==1.8.0.post1
    - astor==0.8.1
    - astunparse==1.6.3
    - beautifulsoup4==4.9.1
    - bqplot==0.12.6
    - branca==0.3.1
    - cdsapi==0.3.0
    - click==7.1.1
    - colour==0.1.5
    - cycler==0.10.0
    - dulwich==0.19.16
    - earthengine-api==0.1.232
    - eli5==0.10.1
    - et-xmlfile==1.0.1
    - folium==0.11.0
    - future==0.18.2
    - gast==0.2.2
    - geeadd==0.4.9
    - geemap==0.7.2
    - geocoder==1.38.1
    - google-api-core==1.14.3
    - google-auth-oauthlib==0.4.1
    - google-cloud-core==1.0.3
    - google-cloud-storage==1.23.0
    - google-pasta==0.2.0
    - google-resumable-media==0.5.0
    - googleapis-common-protos==1.6.0
    - grpcio==1.31.0
    - h5py==2.10.0
    - httplib2shim==0.0.3
    - ipyfilechooser==0.3.4
    - ipyleaflet==0.12.6
    - ipynb-py-convert==0.4.5
    - ipytree==0.1.8
    - jdcal==1.4.1
    - joblib==0.14.1
    - json5==0.9.4
    - jupyterlab==2.1.0
    - jupyterlab-server==1.1.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.1.0
    - lerc==0.1.0
    - llvmlite==0.33.0
    - lml==0.0.9
    - logzero==1.5.0
    - markdown==3.2.2
    - matplotlib==3.1.3
    - mlxtend==0.17.3
    - mss==5.1.0
    - ntlm-auth==1.4.0
    - numba==0.50.0
    - numpy==1.18.5
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - openpyxl==3.0.3
    - opt-einsum==3.3.0
    - pandas==1.0.1
    - pillow==6.2.1
    - protobuf==3.10.0
    - pyexcel==0.5.15
    - pyexcel-io==0.5.20
    - pyshp==2.1.0
    - python-graphviz==0.14
    - rastertodataframe==0.2.1
    - ratelim==0.1.6
    - requests-kerberos==0.12.0
    - requests-ntlm==1.1.0
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - rfpimp==1.3.5
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - seaborn==0.10.0
    - selenium==3.141.0
    - sklearn==0.0
    - soupsieve==2.0.1
    - stratx==0.4
    - tabulate==0.8.7
    - tensorboard==2.0.2
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.0.0
    - tensorflow-estimator==2.0.1
    - termcolor==1.1.0
    - texttable==1.6.2
    - tqdm==4.48.2
    - traittypes==0.2.1
    - werkzeug==1.0.1
    - winkerberos==0.7.0
    - xarray==0.15.1
    - xlrd==1.2.0
prefix: C:\Users\wangj\Anaconda3\envs\ee_py3

